export const LOGIN_USER_API = "/api/v1/cms/login";
export const GET_INFO_ACCOUNT = "/api/v1/cms/me";
export const GET_LIST_USER = "/api/v1/cms/users";
export const GET_STATISTICAL_USER = "/api/v1/cms/analytic/user";
export const GET_USER_DETAIL = user_id => `/api/v1/cms/user/${user_id}/detail`;
export const UPDATE_USER_INFO = user_id => `/api/v1/cms/user/${user_id}/update`;
export const BLOCK_USER = user_id => `/api/v1/cms/user/${user_id}/change-status`;
export const GET_REPORT_USER_LIST = "/api/v1/cms/user/reports";
export const DELETE_USER = user_id => `/api/v1/cms/user/${user_id}/report/delete`;
export const UPLOAD_MEDIA = "/api/v1/general/upload";
